-- DDL para Oracle 12c+ (coluna IDENTITY)
-- Execute no schema desejado (usuário conectado)
-- Observação: use VARCHAR2 em vez de VARCHAR e NUMBER(1) para boolean

CREATE TABLE Usuarios (
    Id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Nome VARCHAR2(100) NOT NULL,
    Email VARCHAR2(100) NOT NULL,
    Senha VARCHAR2(255) NOT NULL,
    Ativo NUMBER(1) DEFAULT 1 NOT NULL, -- 1 = true, 0 = false
    Perfil VARCHAR2(50) NOT NULL,       -- 'normal' ou 'admin'
    DataCriacao DATE DEFAULT SYSDATE NOT NULL
);

-- Constraint de unicidade no email
ALTER TABLE Usuarios ADD CONSTRAINT UQ_Usuarios_Email UNIQUE (Email);


INSERT INTO Usuarios (Nome, Email, Senha, Ativo, Perfil, DataCriacao)
VALUES ('leonardo', 'leo.vsanto@hotmail.com', '123', 1, 'normal', DATE '2026-06-05');

INSERT INTO Usuarios (Nome, Email, Senha, Ativo, Perfil, DataCriacao)
VALUES ('Paula', 'paula.miekusz@hotmail.com', '456', 1, 'admin', DATE '2026-06-05');


-- Oracle 12c+ (coluna IDENTITY)
-- Execute no schema/usuário desejado

CREATE TABLE Formulario (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomeContratada VARCHAR2(255) NOT NULL,
    numeroContrato VARCHAR2(50) NOT NULL,
    localEscopo VARCHAR2(255) NOT NULL,
    representante VARCHAR2(255),
    siglaArea NUMBER,
    areaGestora NUMBER,
    identificadorAreaGestora VARCHAR2(255),
    siglaAreaGestora VARCHAR2(255),
    supervisoraAmbiental VARCHAR2(255),
    autorCadastramento VARCHAR2(255),
    responsavelTecnico VARCHAR2(255),
    registroProfissional VARCHAR2(255),
    documentoResponsabilidadeTecnica VARCHAR2(255),
    naturezaPGA NUMBER,
    tipoFormulario VARCHAR2(255),
    dataEmissaoFormulario DATE,
    numeroFormulario NUMBER,
    autorFormulario VARCHAR2(255),
    arquivoFDC VARCHAR2(255),
    codigoFDC NUMBER,
    dataCadastramento DATE DEFAULT SYSDATE,
    horaCadastramento VARCHAR2(8),
    chavePrimaria VARCHAR2(255),
    elementoMonitoramentoNumero NUMBER,
    elementoMonitoramentoNome VARCHAR2(255),
    municipio NUMBER,
    linhaCPTM NUMBER,
    nomeEstacaoCPTM NUMBER,
    numeroViaLinha NUMBER,
    trechoSentidoLinha NUMBER,
    quilometroPoste VARCHAR2(255),
    latitude NUMBER(10,7),
    longitude NUMBER(10,7),
    atividade NUMBER,
    atividadeNaoListada VARCHAR2(255),
    draListado NUMBER,
    draNaoListada VARCHAR2(255),
    codigoDRA NUMBER,
    dataValidadeDRA DATE,
    TipoAtividadeCPTM NUMBER,
    NomeEdificacao NUMBER,
    NomeEdificacaoComplemento VARCHAR2(255),
    OrigemEfluente NUMBER,
    FonteGeradoraEfluente NUMBER,
    QuantidadeEfluente NUMBER,
    TipoDestinacaoEfluente NUMBER,
    TipoVeiculo NUMBER,
    IdentificadorVeiculo VARCHAR2(255),
    codigoGuiaRemessa VARCHAR2(255),
    distanciaViaCPTM NUMBER,
    observacoesGerais CLOB,
    fotografia1 BLOB,
    fotografia2 BLOB,
    fotografia3 BLOB,
    fotografia4 BLOB,
    usuario_id NUMBER NOT NULL,
    CONSTRAINT FK_Formulario_Usuario FOREIGN KEY (usuario_id) REFERENCES Usuarios(Id)
);


-- Índice sugerido para consultas por usuário - acabei n colocando no modelo relacional, mas pode ajudar na performance
CREATE INDEX IDX_Formulario_Usuario ON Formulario(usuario_id);